"""Add JoinRequest.response_message

Revision ID: 0907342e4a03
Revises: 4e00e649463b
Create Date: 2026-07-28 17:53:49.820657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0907342e4a03'
down_revision: Union[str, Sequence[str], None] = '4e00e649463b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('response_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_requests', 'response_message')
    # ### end Alembic commands ###
