"""Add Group.description

Revision ID: 13be12bc53df
Revises: 8ad47e06b5b7
Create Date: 2026-07-20 16:00:27.994826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13be12bc53df'
down_revision: Union[str, Sequence[str], None] = '8ad47e06b5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###
