"""Add PostRead and CommentRead

Revision ID: 17d300563198
Revises: bc7bd23a2927
Create Date: 2026-08-02 19:46:06.922708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d300563198'
down_revision: Union[str, Sequence[str], None] = 'bc7bd23a2927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_post_read_user_post')
    )
    op.create_index(op.f('ix_post_reads_post_id'), 'post_reads', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_reads_user_id'), 'post_reads', ['user_id'], unique=False)
    op.create_table('comment_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='uq_comment_read_user_comment')
    )
    op.create_index(op.f('ix_comment_reads_comment_id'), 'comment_reads', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_reads_user_id'), 'comment_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_reads_user_id'), table_name='comment_reads')
    op.drop_index(op.f('ix_comment_reads_comment_id'), table_name='comment_reads')
    op.drop_table('comment_reads')
    op.drop_index(op.f('ix_post_reads_user_id'), table_name='post_reads')
    op.drop_index(op.f('ix_post_reads_post_id'), table_name='post_reads')
    op.drop_table('post_reads')
    # ### end Alembic commands ###
