"""Add User.feed_baseline_at

Revision ID: 202fe15542ea
Revises: f3ccfd4d8c49
Create Date: 2026-08-06 11:38:39.356853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202fe15542ea'
down_revision: Union[str, Sequence[str], None] = 'f3ccfd4d8c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feed_baseline_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET feed_baseline_at = NOW() WHERE feed_baseline_at IS NULL")
    op.alter_column(
        'users', 'feed_baseline_at',
        existing_type=sa.DateTime(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feed_baseline_at')
    # ### end Alembic commands ###
