"""Add Contact model, Loan.contact_id, borrower_id nullable

Revision ID: 37a743bb6d2a
Revises: d975de06bb73
Create Date: 2026-07-25 11:07:44.977412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37a743bb6d2a'
down_revision: Union[str, Sequence[str], None] = 'd975de06bb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_owner_id'), 'contacts', ['owner_id'], unique=False)
    op.add_column('loans', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.alter_column('loans', 'borrower_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_loans_contact_id'), 'loans', ['contact_id'], unique=False)
    op.create_foreign_key(None, 'loans', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_index(op.f('ix_loans_contact_id'), table_name='loans')
    op.alter_column('loans', 'borrower_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('loans', 'contact_id')
    op.drop_index(op.f('ix_contacts_owner_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
