"""Add Book.borrowing_visibility

Revision ID: 395ff8054616
Revises: 2a8731f2b938
Create Date: 2026-07-30 16:35:25.673889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395ff8054616'
down_revision: Union[str, Sequence[str], None] = '2a8731f2b938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('borrowing_visibility', sa.Enum('club_only', 'public_enquiries_allowed', 'not_available', name='borrowingvisibility', native_enum=False, length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'borrowing_visibility')
    # ### end Alembic commands ###
