"""Add Book.summary and summary_source

Revision ID: 3ae9369bd22f
Revises: b68e5d23832f
Create Date: 2026-07-22 11:17:31.285705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae9369bd22f'
down_revision: Union[str, Sequence[str], None] = 'b68e5d23832f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('summary_source', sa.Enum('owner', 'open_library', 'ai_generated', name='summarysource', native_enum=False, length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'summary_source')
    op.drop_column('books', 'summary')
    # ### end Alembic commands ###
