"""Post: add book_id, post_type; new Comment table

Revision ID: 4d8bd9e3b77a
Revises: 50b3a297117d
Create Date: 2026-07-21 17:53:34.960139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d8bd9e3b77a'
down_revision: Union[str, Sequence[str], None] = '50b3a297117d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('post_type', sa.Enum('general', 'question', 'announcement', name='posttype', native_enum=False, length=20), nullable=False))
    op.alter_column('posts', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_posts_book_id'), 'posts', ['book_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_book_id'), table_name='posts')
    op.alter_column('posts', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('posts', 'post_type')
    op.drop_column('posts', 'book_id')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
