"""Add Book.genre

Revision ID: 50b3a297117d
Revises: c5a44e6fb896
Create Date: 2026-07-21 11:00:15.584741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b3a297117d'
down_revision: Union[str, Sequence[str], None] = 'c5a44e6fb896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.Enum('fantasy', 'science_fiction', 'horror', 'mystery', 'thriller', 'historical_fiction', 'literary_fiction', 'romance', 'adventure', 'dystopia_utopia', 'biography', 'history', 'science', 'philosophy', 'nonfiction', 'poetry', 'drama', 'essay', 'young_adult', 'childrens', 'fairy_tale', 'satire', name='bookgenre', native_enum=False, length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
