"""Group founder+role, JoinRequest, LoanRequest, Book.location

Revision ID: 8ad47e06b5b7
Revises: fccf478215c2
Create Date: 2026-07-20 09:55:52.368964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad47e06b5b7'
down_revision: Union[str, Sequence[str], None] = 'fccf478215c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', 'cancelled', 'expired', name='requeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_group_id'), 'join_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    op.create_table('loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', 'cancelled', 'expired', name='requeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_requests_book_id'), 'loan_requests', ['book_id'], unique=False)
    op.create_index(op.f('ix_loan_requests_requester_id'), 'loan_requests', ['requester_id'], unique=False)
    op.add_column('books', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('group_memberships', sa.Column('role', sa.Enum('founder', 'admin', 'member', name='grouprole', native_enum=False, length=20), nullable=False))
    op.add_column('groups', sa.Column('founder_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['founder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'founder_id')
    op.drop_column('group_memberships', 'role')
    op.drop_column('books', 'location')
    op.drop_index(op.f('ix_loan_requests_requester_id'), table_name='loan_requests')
    op.drop_index(op.f('ix_loan_requests_book_id'), table_name='loan_requests')
    op.drop_table('loan_requests')
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_group_id'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
