"""Add response_read to LoanRequest and JoinRequest

Revision ID: b1e09a2c2d2a
Revises: 0907342e4a03
Create Date: 2026-07-28 18:56:31.651538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e09a2c2d2a'
down_revision: Union[str, Sequence[str], None] = '0907342e4a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('response_read', sa.Boolean(), nullable=False))
    op.add_column('loan_requests', sa.Column('response_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_requests', 'response_read')
    op.drop_column('join_requests', 'response_read')
    # ### end Alembic commands ###
