"""Add BorrowingInquiry, BorrowingInquiryMessage, ClubConversation, ClubConversationMessage

Revision ID: b36ce5b51e59
Revises: 395ff8054616
Create Date: 2026-07-30 16:46:09.873955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36ce5b51e59'
down_revision: Union[str, Sequence[str], None] = '395ff8054616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowing_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowing_inquiries_book_id'), 'borrowing_inquiries', ['book_id'], unique=False)
    op.create_index(op.f('ix_borrowing_inquiries_owner_id'), 'borrowing_inquiries', ['owner_id'], unique=False)
    op.create_index(op.f('ix_borrowing_inquiries_requester_id'), 'borrowing_inquiries', ['requester_id'], unique=False)
    op.create_table('club_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_conversations_group_id'), 'club_conversations', ['group_id'], unique=False)
    op.create_index(op.f('ix_club_conversations_initiator_id'), 'club_conversations', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_club_conversations_recipient_id'), 'club_conversations', ['recipient_id'], unique=False)
    op.create_table('borrowing_inquiry_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['borrowing_inquiries.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowing_inquiry_messages_inquiry_id'), 'borrowing_inquiry_messages', ['inquiry_id'], unique=False)
    op.create_table('club_conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['club_conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_conversation_messages_conversation_id'), 'club_conversation_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_conversation_messages_conversation_id'), table_name='club_conversation_messages')
    op.drop_table('club_conversation_messages')
    op.drop_index(op.f('ix_borrowing_inquiry_messages_inquiry_id'), table_name='borrowing_inquiry_messages')
    op.drop_table('borrowing_inquiry_messages')
    op.drop_index(op.f('ix_club_conversations_recipient_id'), table_name='club_conversations')
    op.drop_index(op.f('ix_club_conversations_initiator_id'), table_name='club_conversations')
    op.drop_index(op.f('ix_club_conversations_group_id'), table_name='club_conversations')
    op.drop_table('club_conversations')
    op.drop_index(op.f('ix_borrowing_inquiries_requester_id'), table_name='borrowing_inquiries')
    op.drop_index(op.f('ix_borrowing_inquiries_owner_id'), table_name='borrowing_inquiries')
    op.drop_index(op.f('ix_borrowing_inquiries_book_id'), table_name='borrowing_inquiries')
    op.drop_table('borrowing_inquiries')
    # ### end Alembic commands ###
