"""Add InquiryStatus to BorrowingInquiry

Revision ID: bc7bd23a2927
Revises: b36ce5b51e59
Create Date: 2026-07-30 17:27:40.227830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7bd23a2927'
down_revision: Union[str, Sequence[str], None] = 'b36ce5b51e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: add_column already succeeded in a previous failed attempt
    # (column exists as nullable) — only backfill + tighten remain.
    op.execute("UPDATE borrowing_inquiries SET status = 'open' WHERE status IS NULL")
    op.alter_column(
        'borrowing_inquiries', 'status',
        existing_type=sa.Enum('open', 'closed', name='inquirystatus', native_enum=False, length=20),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowing_inquiries', 'status')
    # ### end Alembic commands ###
