"""Add ClubInvitation

Revision ID: c2e161b6781c
Revises: 20838036bb40
Create Date: 2026-08-05 22:40:22.255834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e161b6781c'
down_revision: Union[str, Sequence[str], None] = '20838036bb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_invitations_group_id'), 'club_invitations', ['group_id'], unique=False)
    op.create_index(op.f('ix_club_invitations_invited_email'), 'club_invitations', ['invited_email'], unique=False)
    op.create_index(op.f('ix_club_invitations_token'), 'club_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_invitations_token'), table_name='club_invitations')
    op.drop_index(op.f('ix_club_invitations_invited_email'), table_name='club_invitations')
    op.drop_index(op.f('ix_club_invitations_group_id'), table_name='club_invitations')
    op.drop_table('club_invitations')
    # ### end Alembic commands ###
