"""Widen Group.description to 2000 chars

Revision ID: c5a44e6fb896
Revises: 13be12bc53df
Create Date: 2026-07-20 16:37:20.178184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5a44e6fb896'
down_revision: Union[str, Sequence[str], None] = '13be12bc53df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'description',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
