"""Add Loan.condition_rating

Revision ID: d975de06bb73
Revises: 3ae9369bd22f
Create Date: 2026-07-24 15:30:04.181894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd975de06bb73'
down_revision: Union[str, Sequence[str], None] = '3ae9369bd22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('condition_rating', sa.Enum('better_than_before', 'same_condition', 'slightly_worse', 'significantly_worse', name='conditionrating', native_enum=False, length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'condition_rating')
    # ### end Alembic commands ###
