"""Add LoanRequest.response_message

Revision ID: d9fdcdc697db
Revises: f41121712523
Create Date: 2026-07-25 13:45:54.256576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fdcdc697db'
down_revision: Union[str, Sequence[str], None] = 'f41121712523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('response_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_requests', 'response_message')
    # ### end Alembic commands ###
