"""Add User.email_verified and EmailVerificationToken

Revision ID: f2eb21a2bf7f
Revises: 17d300563198
Create Date: 2026-08-03 22:42:16.136267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2eb21a2bf7f'
down_revision: Union[str, Sequence[str], None] = '17d300563198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    # Add as nullable first, so we can backfill existing rows before
    # tightening to NOT NULL — MySQL does not apply the Python-side
    # default to pre-existing rows automatically (see Struktur.md,
    # the 30.07 borrowing_visibility incident).
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # Existing/seeded users are grandfathered in as verified — they
    # predate this feature and should not be locked out.
    op.execute("UPDATE users SET email_verified = TRUE WHERE email_verified IS NULL")
    op.alter_column(
        'users', 'email_verified',
        existing_type=sa.Boolean(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
