"""Add User.email_verified_at and email_verification_method

Revision ID: f3ccfd4d8c49
Revises: c2e161b6781c
Create Date: 2026-08-06 09:39:21.580656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ccfd4d8c49'
down_revision: Union[str, Sequence[str], None] = 'c2e161b6781c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_verification_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_method')
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###
