"""Add LoanRequest.requested_due_date and note

Revision ID: f41121712523
Revises: 37a743bb6d2a
Create Date: 2026-07-25 12:53:49.918908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41121712523'
down_revision: Union[str, Sequence[str], None] = '37a743bb6d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('requested_due_date', sa.Date(), nullable=True))
    op.add_column('loan_requests', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_requests', 'note')
    op.drop_column('loan_requests', 'requested_due_date')
    # ### end Alembic commands ###
